org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.2.0
forge_version_range=[47.2,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=minecart_backport
mod_name=Minecart Backport
mod_license=MIT
mod_version=1.2.0
mod_group_id=com.notunanancyowen
mod_authors=N0t_UN_Owen/NotUnaNancyOwen, MinazukiSora
mod_description=Backports the modern minecart movement mechanics to Minecraft 1.20.1.
